---
title: ''
author: "Gonzalo J. Muoz"
date: "`r Sys.Date()`"
output: html_document
---

## UNDERGRADUATE COURSES

***Notes.*** **Optativo de Formación General = OPR.**

Aprendizaje en organizaciones (OPR) [Learning in Organizacions] (2022 - ?), School of Business, Pontificia Universidad Católica de Chile

Comportamiento Organizacional [Organizational Behavior] (2022 - ?), School of Business, Pontificia Universidad Católica de Chile


Enfoques y Problemas Actuales en Psicología [Perspectives and Current Issues in Psychology] (2021), School of Psychology, Universidad Adolfo Ibáñez
	
Introducción a los Métodos de Investigación [Introduction to Research Methods] (2015 - 2019), School of Psychology, Universidad Adolfo Ibáñez

Nuevos Contextos y Desafíos Organizacionales [Recent Trends and Challenges for Organizations] (2014), School of Psychology, Universidad Adolfo Ibáñez

Teoría y Construcción de Instrumentos [Measurement Theory and Test Construction] (2006 – 2009; 2014 - 2018), School of Psychology, Universidad Adolfo Ibáñez

Métodos de Investigación Cuantitativa en Psicología [Quantitative Research Methods in Psychology] (2006 – 2008; 2014 - 2017), School of Psychology, Universidad Adolfo Ibáñez.

Experimental Psychology (Research Methods). Teaching assistant (August 2011 – December 2013), Department of Psychology, Texas A&M University.

Taller Desarrollo de Carrera y Empleabilidad [Career Development and Employability (workshop)] (2008), School of Business, Universidad Adolfo Ibáñez

## GRADUATE COURSES

Trabajo en Equipo [Teamwork] (2025 - ?). Magíster en Gestión Estratégica de Personas y Comportamiento Organizacional. School of Business and School of Psychology, Pontificia Universidad Católica de Chile.

Gestión del Desempeño [Performance Management] (2025 - ?). Magíster en Gestión Estratégica de Personas y Comportamiento Organizacional. School of Business and School of Psychology, Pontificia Universidad Católica de Chile.

Evidence-based management (2021), Master in Organizational Psychology, School of Psychology, Universidad Adolfo Ibáñez

Cultura y clima organizacional [Organizational cultural and climate] (2020 - 2021), Master in Organizational Psychology, School of Psychology, Universidad Adolfo Ibáñez, Chile.

***
**Para citar el material de clases disponible a continuación por favor usar el siguiente formato**

Muñoz, G. J. (2019-2022). [Curso Estadística Avanzada]. Doctorado en Neurociencia Social y Cognición, Universidad Adolfo Ibáñez, Chile. https://rpubs.com/gmunoz

***

[Estadística avanzada Random Coefficient Models](https://rpubs.com/gmunoz) [Advanced Statistics Random Coefficient Models] (2019 - 2022), Doctorado en Neurociencia Social y Cognición, School of Psychology, Universidad Adolfo Ibáñez

[Estadística avanzada ANOVA](https://rpubs.com/gmunoz) [Advanced Statistics ANOVA] (2019 - 2022), Doctorado en Neurociencia Social y Cognición, School of Psychology, Universidad Adolfo Ibáñez

Entrenamiento [Training] (2014 - 2021), Master in Organizational Psychology, School of Psychology, Universidad Adolfo Ibáñez

Innovaciones Metodológicas para la Toma de Decisiones [Methodological Innovations for Decision Making] (2014 - 2021), Diploma in Strategic Management of Employee Assessment, School of Psychology, Universidad Adolfo Ibáñez
